jsil/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('space.urls')),
    url(r'', include('user.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls',namespace="social")),
    url(r'^accounts/', include('allauth.urls')),

]

space/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib import admin

app_name = 'space'

urlpatterns=[
  url('^$',views.home,name = 'home'),
  url(r'^comment/(?P<product_id>\d+)', views.comment, name='comment'),
  url(r'^like/(?P<product_id>\d+)', views.like, name='like'),

  url(r'category/(?P<name>[-\w]+)',views.filter_by_category,name ='category'),

  url(r'^search/', views.search_results, name='search_results'),
  url(r'^profile/$', views.my_profile, name='my_profile'),


  # url(r'^add-to-cart/(?P<item_id>\d+)/$', views.add, name='add_to_cart'),

  # url(r'^item/delete/(?P<item_id>[-\w]+)/$', views.delete_from_cart, name='delete_item'),
  url(r'^shoppingcart/remove/(?P<item_id>\d+)/$',views.remove,name='remove_from_cart'),
  url(r'^home/$', views.Home, name='chat'),
  url(r'^post/$', views.Post, name='post'),
  url(r'^messages/$', views.Messages, name='messages'),


  url(r'^cart/$',views.show,name='cart'),

  # url(r'^checkout/$', views.checkout, name='checkout'),
  url(r'^order-summary/$', views.order_details, name="order_summary"),
  url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name="add_to_cart"),
  # url(r'^item/delete/(?P<item_id>[-\w]+)/$', views.delete_from_cart, name='delete_item'),
  # url(r'^checkout/$', views.checkout, name='checkout'),
  url(r'^daraja/stk-push', views.stk_push_callback, name='mpesa_stk_push_callback'),
  url(r'^cart/daraja/push', views.push, name='push_callback'),


]
def __unicode__(self):
   return self.message

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns=[
    url(r'^proceed/order/$', views.orders, name='orders'),
    url(r'^orders/supplier/$', views.supplier, name='supplier'),
    url(r'^space/orders/history$', views.order_history, name='order_history'),
    url(r'^space/orders/order_details/(\d+)$', views.order_details, name='order_details'),
    url(r'^space/receipt/$', views.receipt, name='receipt'),
    url(r'^orders/order/(?P<item_id>\d+)$', views.selected, name='selected'),
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

space/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ImageForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude =['posted_on','likes','user',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [ 'comment' ]

class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

space/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib.auth.models import User # May not be in use
from django.http  import HttpResponse,Http404,HttpResponseRedirect,HttpResponseForbidden,JsonResponse
from django.contrib.auth import login, authenticate, get_user_model
import json
from jsil import settings
import urllib
from django.contrib import messages
from .forms import SignupForm,CommentForm,ComposeForm,ImageForm
from .models import *
from django.contrib import messages
from django.conf import settings
import requests
from .decorators import check_recaptcha
from django.http import JsonResponse
from django.views.generic import DetailView, ListView
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
# from .models import Thread, ChatMessage



# django - carton 
from carton.cart import Cart
from django_daraja.mpesa.core import MpesaClient

#
from django.views import generic
from multiprocessing import Process

import csv





from django.urls import reverse

@login_required(login_url='/accounts/login/')
def home(request):
    products = Product.objects.all()
    comments = Comment.objects.all()
    likes = Likes.objects.all()
    return render(request, 'home.html',locals())
    
def signup(request):

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
  
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''

            if result['success']:
                form.save()
                messages.success(request, 'Account verified successfully!')
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')

            return redirect('homepage')
    else:
        form = SignupForm()

    return render(request, 'registration/registration_form.html', {'form': form})

@check_recaptcha
def signup(request):

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid() and request.recaptcha_is_valid:
            form.save()
            messages.success(request, 'Account created successfully!')
            return redirect('homepage')
    else:
        form = SignupForm()

    return render(request, 'registration/registration_form.html', {'form': form})

@login_required(login_url='/accounts/login/')
def comment(request, product_id):
    products = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.product = products
            comment.save()
    return redirect('homepage')


@login_required(login_url='/accounts/login/')
def like(request, product_id):
    current_user = request.user
    liked_product=Product.objects.get(id=product_id)
    new_like,created= Likes.objects.get_or_create(who_liked=current_user, liked_product=liked_product)
    new_like.save()

    return redirect('homepage')



def filter_by_category(request,name):
    '''
    Filters the database and displays products according to category_id
    '''
    products = Product.filter_by_category(name)
    print(name)
    print(products)

    return render(request,'category.html',{"products":products})




def my_profile(request):
    my_user_profile = Profile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
    context = { 'my_orders': my_orders }
    return render(request, "profile.html", context)


def stk_push_callback(request):
        data = request.body
        cart = Cart(request.session)

        product = Product.objects.get(id=item_id)
        print(product)

        cart.add(product, price=product.price)

        print(cart.items)

        return redirect('space:category',name=product.category)

def add_to_cart(request,item_id):

    cart = Cart(request.session)

    product = Product.objects.get(id=item_id)
    print(product)

    cart.add(product, price=product.price)

    print(cart.items)

    return redirect('space:category',name=product.category)


def show(request):
    cart = Cart(request.session)
    products = Product.objects.all()
    total=cart.total
    # subtotal=cart.subtotal()

    return render(request, 'cart.html', locals()) 
def order_details(request, item_id=None):
    x = Order.objects.get(pk=item_id)
    selected = Product.objects.filter(px__kx=x)

    print ( [i.price for i in selected] )

    total = sum([i.price for i in selected])

    # total = ( i.price for i in selected)
    # print( total )
    
    return render(request, 'orders/see_more.html', locals())


def remove(request, item_id):
    '''
    Controller function for removing an item from the cart.
    '''
    cart = Cart(request.session)
    product = Product.objects.get(id=item_id)
    cart.remove(product)
    return render(request, 'cart.html', locals())


@login_required(login_url='/accounts/login/')
def search_results(request):
  if 'product' in request.GET and request.GET["product"]:
    name = request.GET.get("product")
    searched_products = Product.search_products(name)
    message = f"{name}"

    return render(request, 'search.html',{"message":message,"products":searched_products})

  else:
    message = "You haven't searched for anything"
    return render(request, 'search.html',{"message":message})

def Home(request):
    c = Chat.objects.all()
    return render(request, "chat.html", {'home': 'active', 'chat': c})

def Post(request):
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        
        c = Chat(user=request.user, message=msg)
            
        
        msg = c.user.username+": "+msg

        c = Chat(user=request.user, message=msg)

        if msg != '':            
            c.save()
        return JsonResponse({ 'msg': msg, 'user': c.user.username})
    else:
        return HttpResponse('Request must be POST.')

def Messages(request):
    c = Chat.objects.all()
    return render(request, 'messages.html', {'chat': c})

def push(request):
   cl = MpesaClient()

   phone_number = '0711419032'
   amount = 1
   account_reference = 'JSIL Space Solutions'
   transaction_desc = 'Test Description'
   callback_url = 'https://4a83e24a.ngrok.io/http://127.0.0.1:8000/daraja/stk-push'
   response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
   print(response)
   return HttpResponse(response.text)

space/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- background-color:#27AE60;color: white -->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
<!------ Include the above in your HEAD tag ---------->


<style>
    
    * {
        /* font-family: 'Pacifico', cursive; */
        font-family: 'Josefin Sans', sans-serif;
    }
    .fresh {
        background-color: rgb(211, 71, 94) !important;
        color: white;
        font-size: 14px;
    }

    
    .menu {
        background-color: #EAEDED;
        color: #333
    }
    
    .menu:hover {
        color: rgb(211, 71, 94);
    }
</style>
{% include 'navbar.html' %}
<div class="container-fluid">
    <div class="container">
        <h3 style="background-color:rgb(94, 45, 114);color: white;font-family: 'Josefin Sans', sans-serif;" class="h3 list-group-item list-group-item-action">
            Your Cart <i class="fas fa-shopping-cart"></i>
        </h3>
        <div class="row">
                <div class="col-xs-12 col-sm-3">
                        <div class="list-group">
                            <span style="background-color:rgb(94, 45, 114);color:white" href="#" class="list-group-item text-center menu">
                                <i class="fab fa-buromobelexperte"></i> Menu
                            </span>
                            <a href="{% url 'space:cart' %}" class="list-group-item menu">
                                <i class="fas fa-shopping-cart"></i> Cart
                                <span class="badge badge-primary badge-pill fresh">
                                    {% if cart.items %} {{ cart.items |length }} {% else %} 0 {% endif %}
                                </span>
                            </a>
                            <a href="{% url 'user:order_history' %}" class="list-group-item menu">
                                <i class="fas fa-edit"></i> Order History
                            </a>
                            <a href="" class="list-group-item menu">
                                <i class="fas fa-shopping-basket"></i> Available Products
                            </a>
                            
                        </div><!-- /list-group -->
                    </div>
            
            <div class="col-xs-12 col-sm-12 col-md-8">
                <table class="table table-hover">
                    
                    <thead>
                        
                        <tr style="background-color:rgb(94, 45, 114);color: white">
                            <br>
                            <th>Product</th>
                          
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Total</th>
                            <th class="text-center">Price</th>

                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% for item in cart.items %}
                        
                        <tr>
                            
                            <td class="col-sm-12 col-md-4 col-xs-12">
                                
                                <div class="media">
                                    
                                    <a class="thumbnail pull-left" href="#"> <img class="media-object" src="{{ item.product.post.url }}"> </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a style="color:rgb(94, 45, 114);;" href="#">{{ item.product.name }}</a></h4>
                                        <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-1 col-md-1 text-center"><strong></strong></td>

                            <td class="col-sm-1 col-md-1 text-center"><strong>KSh {{ item.product.price }}</strong></td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>KSh {{ item.subtotal }}</strong></td>
                            <td class="col-sm-1 col-md-1">
                                <button style="background-color:rgb(211, 71, 94);" type="button" class="btn btn-success">
                                    <a style="color:white;" href="/shoppingcart/remove/{{ item.product.id }}">
                                        <span class="glyphicon glyphicon-remove"></span> Remove
                                    </a>
                                </button></td>
                            </tr>
                            
                            {%endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>   </td>
                                <td>   </td>
                                <td>   </td>
                                <td>
                                    <h4 style="font-family: 'Josefin Sans', sans-serif;">Total</h4>
                                    <br>
                                </td>
                                <td class="">
                                    <h4>
                                        <strong>KSh {{total}}<br></strong>
                                        <br>
                                        
                                    </h4>
                                </td>
                            </tr>
                            <tr>
                                <td>   </td>
                                <td>   </td>
                                <td>   </td>
                                <td>
                                    <a type="button" href="{% url 'space:home' %}" class="btn btn-success">
                                        <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
                                    </a></td>
                                    <td>
                                        <button type="button" style="background-color:rgb(211, 71, 94);height:36px;border-radius:5px;">
                                            <a href="daraja/push" style="color:whitesmoke;">
                                                Checkout <span class="glyphicon glyphicon-play"></span>
                                            </a>
                                        </button></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <style>
                
            </style>
            {% endblock %}

space/templates/order-details.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{{ block.super }}
{% load carton_tags %}
{% get_cart as cart %}

{% include 'navbar.html' %}
<style>
    .ctitle {
        font-family: 'Josefin Sans', sans-serif;
    }

    * {
        /* font-family: 'Pacifico', cursive; */
        font-family: 'Josefin Sans', sans-serif;
    }

    .product-grid {
        border-radius: 10px;

    }

    ul.dropdown-cart {
        min-width: 250px;
    }

    ul.dropdown-cart li .item {
        display: block;
        padding: 3px 10px;
        margin: 3px 0;
    }

    ul.dropdown-cart li .item:hover {
        background-color: #f3f3f3;
    }

    ul.dropdown-cart li .item:after {
        visibility: hidden;
        display: block;
        font-size: 0;
        content: " ";
        clear: both;
        height: 0;
    }

    ul.dropdown-cart li .item-left {
        float: left;
    }

    ul.dropdown-cart li .item-left img,
    ul.dropdown-cart li .item-left span.item-info {
        float: left;
    }

    ul.dropdown-cart li .item-left span.item-info {
        margin-left: 10px;
    }

    ul.dropdown-cart li .item-left span.item-info span {
        display: block;
    }

    ul.dropdown-cart li .item-right {
        float: right;
    }

    ul.dropdown-cart li .item-right button {
        margin-top: 14px;
    }

    .fresh {
        background-color: #27AE60;
        color: white
    }

    .menu {
        background-color: #EAEDED;
        color: #333
    }

    .menu:hover {
        color: #27AE60
    }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <h3 style="background-color:#27AE60;color: white" class="h3 list-group-item list-group-item-action">
        order details <i class="far fa-edit"></i>
    </h3>

    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="list-group">
                    <span style="background-color:#27AE60;color:white" href="#" class="text-center list-group-item">
                        <i class="fab fa-buromobelexperte"></i> Menu
                    </span>
                    <a href="{% url 'space:cart' %}" class="list-group-item menu">
                        <i class="fas fa-shopping-cart"></i> Cart
                        <span class="badge badge-primary badge-pill fresh">
                            {% if cart.items %} {{ cart.items |length }} {% else %} 0 {% endif %}
                        </span>
                    </a>
                    <a href="{% url 'space:order_history' %}" class="list-group-item menu">
                        <i class="fas fa-edit"></i> fridge Orders
                    </a>
                    <a href="" class="list-group-item menu">
                        <i class="fas fa-shopping-basket"></i> smart Grocery
                    </a>


                </div><!-- /list-group -->
            </div><!-- /col -->
            <div class="col-xs-12 col-sm-9">

                <div class="row">
                    <div class="col-sm-1"></div>

                    <div class="col-xs-12 col-sm-10" id="vegetables">
                        {% if selected %} {% for item in selected %}
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ item }}
                                <span class=""> {{ item.quantity }} @   KES <strong>{{ item.price }}</strong> </span>
                            </li>
                        </ul>
                        {% endfor %}{% endif %}

                        <div class="list-group-item d-flex justify-content-between align-items-center">
                            <p> Total Cost: KES <strong> {{ total }} </strong> </p>
                        </div>
                        <div class="list-group-item d-flex justify-content-between align-items-center">
                            <p> Order by: {{user.username}}</p>
                        </div>
                    </div>

                    <div class="col-sm-1"></div>
                    <!-- /col -->
                </div>

            </div><!-- /container -->
        </div>
    </div>
</div>

{% endblock %}

space/templates/order-history.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{{ block.super }}
{% load carton_tags %}
{% get_cart as cart %}

{% include 'navbar.html' %}
<br>
<br>
<style>
    .ctitle {
        font-family: 'Josefin Sans', sans-serif;
    }

    * {
        /* font-family: 'Pacifico', cursive; */
        font-family: 'Josefin Sans', sans-serif;
    }

    .product-grid {
        border-radius: 10px;

    }

    ul.dropdown-cart {
        min-width: 250px;
    }

    ul.dropdown-cart li .item {
        display: block;
        padding: 3px 10px;
        margin: 3px 0;
    }

    ul.dropdown-cart li .item:hover {
        background-color: #f3f3f3;
    }

    ul.dropdown-cart li .item:after {
        visibility: hidden;
        display: block;
        font-size: 0;
        content: " ";
        clear: both;
        height: 0;
    }

    ul.dropdown-cart li .item-left {
        float: left;
    }

    ul.dropdown-cart li .item-left img,
    ul.dropdown-cart li .item-left span.item-info {
        float: left;
    }

    ul.dropdown-cart li .item-left span.item-info {
        margin-left: 10px;
    }

    ul.dropdown-cart li .item-left span.item-info span {
        display: block;
    }

    ul.dropdown-cart li .item-right {
        float: right;
    }

    ul.dropdown-cart li .item-right button {
        margin-top: 14px;
    }

    .fresh {
        background-color: #27AE60;
        color: white
    }

    .menu {
        background-color: #EAEDED;
        color: #333
    }

    .menu:hover {
        color: #27AE60
    }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <h3 style="background-color:#27AE60;color: white" class="h3 list-group-item list-group-item-action">
        <i class="fas fa-list-alt"></i> order history
    </h3>

    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="list-group">
                    <span style="background-color:#27AE60;color:white" href="#" class="text-center list-group-item">
                        <i class="fab fa-buromobelexperte"></i> Menu
                    </span>
                    <a href="{% url 'space:cart' %}" class="list-group-item menu">
                        <i class="fas fa-shopping-cart"></i> Cart
                        <span class="badge badge-primary badge-pill fresh">
                            {% if cart.items %} {{ cart.items |length }} {% else %} 0 {% endif %}
                        </span>
                    </a>
                    <a href="{% url 'space:order_history' %}" class="list-group-item menu">
                        <i class="fas fa-edit"></i> fridge Orders
                    </a>
                    <a href="" class="list-group-item menu">
                        <i class="fas fa-shopping-basket"></i> smart Grocery
                    </a>
            
              

                </div><!-- /list-group -->
            </div><!-- /col -->
            <div class="col-xs-12 col-sm-9">

                <div class="row">
                    <div class="col-sm-1"></div>

                    <div class="col-xs-12 col-sm-10" id="vegetables">
                        {% if orders %} {% for order in orders %}
                        <ul class="list-group">


                            <a href="/jsil/orders/order_details/{{order.id}}">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ order }}
                                    <span class=""> {{ order.order_date }} </span>
                                </li>
                            </a>


                        </ul>
                        {% endfor %}
                        {% else %}

                            <div class="alert alert-dismissible alert-primary">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <strong>Oh snap!</strong> no orders made so far !
                            </div>
                        {% endif %}

                    </div>




                    <div class="col-sm-1"></div>
                    <!-- /col -->
                </div>

            </div><!-- /container -->
        </div>
    </div>
</div>

{% endblock %}

space/templates/receipt.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{{ block.super }}
{% load carton_tags %}
{% get_cart as cart %}

{% include 'navbar.html' %}


<br>
<br>
<style>
    .ctitle {
        font-family: 'Josefin Sans', sans-serif;
    }

    * {
        /* font-family: 'Pacifico', cursive; */
        font-family: 'Josefin Sans', sans-serif;
    }

    .product-grid {
        border-radius: 10px;

    }

    ul.dropdown-cart {
        min-width: 250px;
    }

    ul.dropdown-cart li .item {
        display: block;
        padding: 3px 10px;
        margin: 3px 0;
    }

    ul.dropdown-cart li .item:hover {
        background-color: #f3f3f3;
    }

    ul.dropdown-cart li .item:after {
        visibility: hidden;
        display: block;
        font-size: 0;
        content: " ";
        clear: both;
        height: 0;
    }

    ul.dropdown-cart li .item-left {
        float: left;
    }

    ul.dropdown-cart li .item-left img,
    ul.dropdown-cart li .item-left span.item-info {
        float: left;
    }

    ul.dropdown-cart li .item-left span.item-info {
        margin-left: 10px;
    }

    ul.dropdown-cart li .item-left span.item-info span {
        display: block;
    }

    ul.dropdown-cart li .item-right {
        float: right;
    }

    ul.dropdown-cart li .item-right button {
        margin-top: 14px;
    }

    .fresh {
        background-color: #27AE60;
        color: white
    }

    .menu {
        background-color: #EAEDED;
        color: #333
    }

    .menu:hover {
        color: #27AE60
    }
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <h3 style="background-color:#27AE60;color: white" class="h3 list-group-item list-group-item-action">
        <i class="far fa-file-alt"></i> Receipt
    </h3>

    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="list-group">
                    <span style="background-color:#27AE60;color:white" href="#" class="text-center list-group-item">
                        <i class="fab fa-buromobelexperte"></i> Menu
                    </span>
                    <a href="{% url 'space:cart' %}" class="list-group-item menu">
                        <i class="fas fa-shopping-cart"></i> Cart
                        <span class="badge badge-primary badge-pill fresh">
                            {% if cart.items %} {{ cart.items |length }} {% else %} 0 {% endif %}
                        </span>
                    </a>
                    <a href="{% url 'space:order_history' %}" class="list-group-item menu">
                        <i class="fas fa-edit"></i> fridge Orders
                    </a>
                    <a href="" class="list-group-item menu">
                        <i class="fas fa-shopping-basket"></i> smart Grocery
                    </a>

                </div><!-- /list-group -->
            </div><!-- /col -->
            <div class="col-xs-12 col-sm-9">

                <div class="row">
                    <div class="col-sm-1"></div>

                    <div class="col-xs-12 col-sm-10" id="vegetables">

                        <div class="alert alert-dismissible alert-success">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                             {{ message }}
                             <!-- <a href="#" class="alert-link">  </a>. -->
                        </div>


                        {% if cart %} {% for item in cart.items %}
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ item.product.name }}
                                <span class=""> {{ item.quantity }} @ KES <strong>{{ item.product.price }}</strong> </span>
                            </li>
                        </ul>
                        {% endfor %}{% endif %}

                        <div class="list-group-item d-flex justify-content-between align-items-center">
                            <p> Total Cost: KES <strong> {{ cart.total }} </strong> </p>
                        </div>
                    </div>

                    <div class="col-sm-1"></div>
                    <!-- /col -->
                </div>

            </div><!-- /container -->
        </div>
    </div>
</div>

{% endblock %}